name: nanoGPT
channels:
  - pytorch
  # - nvidia
  - conda-forge
  - defaults
dependencies:
  - git
  - jq
  - pip
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.6
  - pip:
    - datasets    
    - tiktoken    
    - wandb    
    - tqdm
    - transformers
  # - pytorch-cuda=11.6
  # - pytorch
  # - numpy
  # - numba
  # - pip:
  #   - datasets    
  #   - tiktoken    
  #   - wandb    
  #   - tqdm    
  #   - numpy-quaternion
  #   - matplotlib
  #   - polyscope
  #   - contexttimer
  #   - sympy
  #   - jupyter
  #   - jupyterlab
  #   - pandas
  #   - openai
  #   - gradio
  #   - python-dotenv 
  #   - lark
  #   